In [1]:
import pandas as pd

In [11]:
filePath = "../data/SFMTA_-_Parking_Citations_&_Fines_20260209 (1).csv"
df = pd.read_csv(filePath, index_col= 0)
df

/var/folders/ys/_jtkggyd0hn93xqgmvmv3yy00000gp/T/ipykernel_77752/1348583001.py:2: DtypeWarning: Columns (9,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filePath, index_col= 0)

,Citation Issued DateTime,Violation,Violation Description,Citation Location,Vehicle Plate State,Vehicle Plate,Fine Amount,Date Added,geom,supervisor_district,analysis_neighborhood,Latitude,Longitude
Citation Number,,,,,,,,,,,,,
"""11560780T",2026 Feb 04 07:56:00 PM,TRC7.2.101A,FAIL DISPL,NaN,NaN,NaN,$0,2026 Feb 09 12:00:00 AM,NaN,NaN,NaN,NaN,NaN
"""11560776T",2026 Feb 04 07:52:00 PM,TRC7.2.101A,FAIL DISPL,NaN,NaN,NaN,$0,2026 Feb 09 12:00:00 AM,NaN,NaN,NaN,NaN,NaN
"""11561605T",2026 Feb 04 07:41:00 PM,TRC7.2.101A,FAIL DISPL,METRO FOREST HILL STATION-DOWNTOWN,NaN,NaN,$134,2026 Feb 09 12:00:00 AM,NaN,NaN,NaN,NaN,NaN
"""11553500T",2026 Feb 04 07:41:00 PM,TRC7.2.101A,FAIL DISPL,NaN,NaN,NaN,$0,2026 Feb 09 12:00:00 AM,NaN,NaN,NaN,NaN,NaN
"""998115893",2026 Feb 04 07:40:00 PM,TRC7.2.40,PRK PROHIB,101 05TH ST,AL,3A0C313,$108,2026 Feb 09 12:00:00 AM,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34796366T,2016 Jan 01 09:41:00 PM,TRC7.2.101C,UNAUTHFARE,CIVIC CENTER,NaN,NaN,$112,2018 Aug 06 12:00:00 AM,POINT (-122.41682999999995 37.77863000000008),6.0,Tenderloin,POINT(-122.41682999999995 37.77863000000008),POINT(-122.41682999999995 37.77863000000008)
34791142T,2016 Jan 01 09:39:00 PM,TRC7.2.101C,FAILTODISP,SEOCNDARY MEZZNAINE,NaN,NaN,$112,2016 Jan 01 12:00:00 AM,POINT (-122.40810999999997 37.782620000000065),6.0,South of Market,POINT(-122.40810999999997 37.782620000000065),POINT(-122.40810999999997 37.782620000000065)
34791131T,2016 Jan 01 09:36:00 PM,TRC7.2.101C,UNAUTHFARE,SECONDARY MEZZANINE,NaN,NaN,$112,2018 Aug 06 12:00:00 AM,POINT (-122.40810999999997 37.782620000000065),6.0,South of Market,POINT(-122.40810999999997 37.782620000000065),POINT(-122.40810999999997 37.782620000000065)
863022790,2016 Jan 01 09:34:00 PM,V22500E,DRIVEWAY,1674 27TH AVE,CA,6LUG065,$106,2020 Apr 30 12:00:00 AM,NaN,NaN,NaN,NaN,NaN
1004469012,2016 Jan 01 09:27:00 PM,V21113A,SCH/PUB GD,375 LAGUNA HONDA,CA,7SVC283,$73,2017 Jan 27 12:00:00 AM,POINT (-122.45581098899999 37.74879299500003),7.0,Twin Peaks,POINT(-122.45581098899999 37.74879299500003),POINT(-122.45581098899999 37.74879299500003)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12303688 entries, "11560780T to 1004469012
Data columns (total 13 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Citation Issued DateTime  object
 1   Violation                 object
 2   Violation Description     object
 3   Citation Location         object
 4   Vehicle Plate State       object
 5   Vehicle Plate             object
 6   Fine Amount               object
 7   Date Added                object
 8   geom                      object
 9   supervisor_district       float64
 10  analysis_neighborhood     object
 11  Latitude                  object
 12  Longitude                 object
dtypes: float64(1), object(12)
memory usage: 1.3+ GB

In [13]:
df["Violation"].nunique()

217

In [15]:
df["Violation"].value_counts()

Violation
TRC7.2.22     5230360
TRC7.2.23B    1294303
TRC7.2.20     1104377
TRC7.2.23A     563936
V5200          294274
               ...
TRC7.2.48           1
PK6.01E             1
V22511.57A          1
TRC7.2.85           1
101                 1
Name: count, Length: 217, dtype: int64

In [ ]:
df["Vehicle Plate"].nunique()

3224792

In [17]:
df["Vehicle Plate"].value_counts()

Vehicle Plate
70358W1    1231
23801V1    1150
11932J2    1130
70509Z1    1050
70302Z1     961
           ...
2J05V7        1
6PDJ138       1
CU53V35       1
MIB652        1
7SVC283       1
Name: count, Length: 3224792, dtype: int64

In [22]:
FineAmount = df["Fine Amount"]
FineAmount[:10]

Citation Number
"11560780T      $0
"11560776T      $0
"11561605T    $134
"11553500T      $0
"998115893    $108
"11557501T    $134
"997794431    $108
"11565492T    $134
"997736305    $108
"11554701T    $134
Name: Fine Amount, dtype: object

In [24]:
Total = sum(int(fine.strip('$').replace(",","")) for fine in FineAmount)
print(Total)

1174558848

**One billion, one hundred seventy-four million, five hundred fifty-eight thousand, eight hundred forty-eight**

In [26]:
MostCitationVehicles = df["Vehicle Plate"].value_counts()
MostCitationVehicles.head()

Vehicle Plate
70358W1    1231
23801V1    1150
11932J2    1130
70509Z1    1050
70302Z1     961
Name: count, dtype: int64

In [27]:
topPayer = df[df["Vehicle Plate"] == '70358W1']
topPayer

,Citation Issued DateTime,Violation,Violation Description,Citation Location,Vehicle Plate State,Vehicle Plate,Fine Amount,Date Added,geom,supervisor_district,analysis_neighborhood,Latitude,Longitude
Citation Number,,,,,,,,,,,,,
"""997439914",2026 Jan 28 09:58:00 AM,TRC7.2.23A,METER DTN,109 FRONT ST,CA,70358W1,$108,2026 Feb 02 12:00:00 AM,NaN,NaN,NaN,NaN,NaN
"""997791675",2026 Jan 22 02:47:00 PM,TRC7.2.23A,METER DTN,106 FRONT ST,CA,70358W1,$108,2026 Jan 27 12:00:00 AM,NaN,NaN,NaN,NaN,NaN
"""996205265",2026 Jan 21 09:46:00 AM,TRC7.2.23A,METER DTN,503 BRYANT ST,CA,70358W1,$108,2026 Jan 26 12:00:00 AM,NaN,NaN,NaN,NaN,NaN
"""997439660",2026 Jan 15 09:37:00 AM,V22500I,BUS ZONE,98 PINE ST,CA,70358W1,$443,2026 Feb 03 12:00:00 AM,NaN,NaN,NaN,NaN,NaN
"""996506792",2026 Jan 02 01:46:00 PM,TRC7.2.23A,METER DTN,106 FRONT ST,CA,70358W1,$108,2026 Feb 03 12:00:00 AM,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
865308592,2016 Feb 23 12:45:00 PM,TRC7.2.23A,METER DTN,123 FRONT ST,CA,70358W1,$78,2020 Apr 30 12:00:00 AM,POINT (-122.39872774499997 37.79262966700003),3.0,Financial District/South Beach,POINT(-122.39872774499997 37.79262966700003),POINT(-122.39872774499997 37.79262966700003)
864966104,2016 Feb 19 11:46:00 AM,TRC7.2.23A,METER DTN,119 FRONT ST,CA,70358W1,$78,2020 Apr 30 12:00:00 AM,POINT (-122.39872052399994 37.792594284000074),3.0,Financial District/South Beach,POINT(-122.39872052399994 37.792594284000074),POINT(-122.39872052399994 37.792594284000074)
864462406,2016 Feb 11 02:24:00 PM,TRC7.2.23A,METER DTN,120 FRONT ST,CA,70358W1,$78,2020 Apr 30 12:00:00 AM,POINT (-122.39861100499996 37.792635062000045),3.0,Financial District/South Beach,POINT(-122.39861100499996 37.792635062000045),POINT(-122.39861100499996 37.792635062000045)
864890530,2016 Jan 28 12:02:00 PM,TRC7.2.23A,METER DTN,119 FRONT ST,CA,70358W1,$78,2020 Apr 30 12:00:00 AM,POINT (-122.39872052399994 37.792594284000074),3.0,Financial District/South Beach,POINT(-122.39872052399994 37.792594284000074),POINT(-122.39872052399994 37.792594284000074)
863844866,2016 Jan 15 12:42:00 PM,TRC7.2.23A,METER DTN,129 FRONT ST,CA,70358W1,$78,2020 Jul 27 12:00:00 AM,POINT (-122.39873857599997 37.79268274100008),3.0,Financial District/South Beach,POINT(-122.39873857599997 37.79268274100008),POINT(-122.39873857599997 37.79268274100008)

In [28]:
totalTopPayer = sum(int(fine.strip("$").replace(",","")) for fine in topPayer["Fine Amount"])
print(totalTopPayer)

119236

In [ ]:
locations = df["Citation Location"]
locations

Citation Number
"11560780T                                   NaN
"11560776T                                   NaN
"11561605T    METRO FOREST HILL STATION-DOWNTOWN
"11553500T                                   NaN
"998115893                           101 05TH ST
                             ...
34796366T                           CIVIC CENTER
34791142T                    SEOCNDARY MEZZNAINE
34791131T                    SECONDARY MEZZANINE
863022790                          1674 27TH AVE
1004469012                      375 LAGUNA HONDA
Name: Citation Location, Length: 12303688, dtype: object

In [32]:
locations.dropna().nunique()

1055053

In [36]:
locations = locations.dropna()

In [37]:
locations.info()

<class 'pandas.core.series.Series'>
Index: 12270397 entries, "11561605T to 1004469012
Series name: Citation Location
Non-Null Count     Dtype
--------------     -----
12270397 non-null  object
dtypes: object(1)
memory usage: 445.2+ MB

In [39]:
locations.head(10)

Citation Number
"11561605T    METRO FOREST HILL STATION-DOWNTOWN
"998115893                           101 05TH ST
"11557501T               VAN NESS AVE & UNION ST
"997794431                          598 28TH AVE
"11565492T                    UNION ST & POLK ST
"997736305                        517 CLAYTON ST
"11554701T                   JUDAH ST & 19TH AVE
"997937916                         18 DELGADO PL
"998275596                      721 TENNESSEE ST
"11564663T               GEARY BLVD & MASONIC ST
Name: Citation Location, dtype: object

In [44]:
streets = locations.astype('string').str.replace(r"\b\d+\b", "", regex= True)
streets.head(10)

Citation Number
"11561605T    METRO FOREST HILL STATION-DOWNTOWN
"998115893                               05TH ST
"11557501T               VAN NESS AVE & UNION ST
"997794431                              28TH AVE
"11565492T                    UNION ST & POLK ST
"997736305                            CLAYTON ST
"11554701T                   JUDAH ST & 19TH AVE
"997937916                            DELGADO PL
"998275596                          TENNESSEE ST
"11564663T               GEARY BLVD & MASONIC ST
Name: Citation Location, dtype: string

In [45]:
streets.value_counts()

Citation Location
 MISSION ST                327667
 CALIFORNIA ST             118934
 SUTTER ST                 117550
 POST ST                   113731
 SACRAMENTO ST             106563
                            ...
NORTH POINT AT COLUMBUS         1
CAPP AT SHITWELL                1
SHITWELL                        1
STOCKTON AT BRODERICK           1
FREELON/ZOE                     1
Name: count, Length: 51415, dtype: Int64